plt.figure(figsize=(10,6))
plt.errorbar([1], [κ_obs], yerr=κ_err, fmt='o', capsize=5, 
             label="DES Y6 (Eridanus)")
plt.axhline(κ_CET, color='r', linestyle='--', label="Predição CET")
plt.axhline(0, color='k', linestyle=':', alpha=0.5)
plt.xticks([])
plt.ylabel("Convergência (κ)")
plt.title("Validação com Dados de Lente Fraca")
plt.legend()
plt.savefig("eridanus_weak_lensing_validation.png")