#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
LOS vs. Hubble residual test using CET linear distance
d_L_CET(z) = (c/H0) * z  [Mpc]
mu_th_CET = 5*log10(d_L_CET) + 25

Inputs:
  - Pantheon CSV (e.g., Pantheon_SH0ES_Data.csv)
      must contain: [CID] or [ID], [zCMB], [MU_SH0ES] (flexible names)
  - los_by_sn.csv (generated by build_los_density_cet.py)
      must contain: [SN_ID], [dens_LOS] and/or [dens_LOS_Kw]

Outputs (in --outdir):
  - merged_for_tests_CET.csv  (merged table with dmu_CET)
  - los_signal_summary_CET.csv (statistical summary)
  - dmu_vs_dens_CET.png (scatter + trend)
  - dmu_binned_CET.csv and dmu_binned_CET.png (quantile-binned means)
"""

import argparse, os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import spearmanr, linregress

C_KMS = 299792.458  # km/s

def pick_col(df, candidates, required=True):
    for c in candidates:
        if c in df.columns:
            return c
    if required:
        raise KeyError(f"Could not find any of the columns: {candidates}")
    return None

def main():
    ap = argparse.ArgumentParser(description="LOS vs Hubble residuals with CET linear distance")
    ap.add_argument("--pantheon", required=True, help="Path to Pantheon CSV")
    ap.add_argument("--loscsv",   required=True, help="Path to LOS-by-SN CSV (from build_los_density_cet.py)")
    ap.add_argument("--outdir",   required=True, help="Output directory")
    ap.add_argument("--H0", type=float, default=70.0, help="H0 in km/s/Mpc (default: 70)")
    ap.add_argument("--dens_col", default="dens_LOS_Kw",
                    help="LOS density column to use (e.g., dens_LOS_Kw or dens_LOS)")
    ap.add_argument("--nbins", type=int, default=8, help="Number of quantile bins for the binned plot")
    args = ap.parse_args()

    os.makedirs(args.outdir, exist_ok=True)

    # --- Pantheon ---
    p = pd.read_csv(args.pantheon)
    id_col = pick_col(p, ["CID", "ID", "sn_id"])
    z_col  = pick_col(p, ["zCMB", "z", "SN_z"])
    mu_obs_col = pick_col(p, ["MU_SH0ES", "mu", "MU"], required=True)

    p = p[[id_col, z_col, mu_obs_col]].rename(
        columns={id_col:"SN_ID", z_col:"z", mu_obs_col:"mu_obs"}
    ).copy()

    # --- CET distance ---
    # d_L_CET [Mpc] = (c/H0) * z
    p["dL_CET_Mpc"] = (C_KMS/args.H0) * p["z"].values
    # mu_th_CET  (if d_L is in Mpc) -> mu = 5*log10(d_L) + 25
    with np.errstate(divide="ignore"):
        p["mu_th_CET"] = 5.0*np.log10(p["dL_CET_Mpc"].clip(lower=1e-9)) + 25.0
    p["dmu_CET"] = p["mu_obs"] - p["mu_th_CET"]

    # --- LOS ---
    los = pd.read_csv(args.loscsv)
    if "SN_ID" not in los.columns:
        raise KeyError("los_by_sn.csv must have an SN_ID column.")
    if args.dens_col not in los.columns:
        raise KeyError(f"Column {args.dens_col} not found in los_by_sn.csv. "
                       f"Available: {list(los.columns)}")

    los_use = los[["SN_ID", args.dens_col]].rename(columns={args.dens_col:"dens"}).copy()

    # --- merge ---
    m = p.merge(los_use, on="SN_ID", how="inner").dropna(subset=["dens", "dmu_CET"])
    m.to_csv(os.path.join(args.outdir, "merged_for_tests_CET.csv"), index=False)

    # --- statistics (Spearman and simple linear regression) ---
    rho, pval = spearmanr(m["dens"], m["dmu_CET"])
    slope, intercept, r, p_lin, _ = linregress(m["dens"], m["dmu_CET"])

    summary = pd.DataFrame({
        "N":[len(m)],
        "spearman_rho":[rho],
        "spearman_p":[pval],
        "lin_slope":[slope],
        "lin_intercept":[intercept],
        "lin_r":[r],
        "lin_p":[p_lin]
    })
    summary.to_csv(os.path.join(args.outdir, "los_signal_summary_CET.csv"), index=False)

    # --- scatter + trend plot ---
    x = m["dens"].values
    y = m["dmu_CET"].values
    xs = np.linspace(np.nanmin(x), np.nanmax(x), 200)
    ys = slope*xs + intercept

    plt.figure(figsize=(9,6))
    plt.scatter(x, y, s=18, alpha=0.75)
    plt.plot(xs, ys)
    ttl = f"Δμ_CET vs {args.dens_col} | Spearman ρ={rho:.2f} (p={pval:.2g})"
    plt.title(ttl)
    plt.xlabel(args.dens_col)
    plt.ylabel("Δμ_CET (mag)")
    plt.tight_layout()
    plt.savefig(os.path.join(args.outdir, "dmu_vs_dens_CET.png"), dpi=160)
    plt.close()

    # --- quantile binning over density ---
    m = m.sort_values("dens").reset_index(drop=True)
    qbins = np.unique(np.quantile(m["dens"], np.linspace(0,1,args.nbins+1)))
    m["bin"] = pd.cut(m["dens"], bins=qbins, include_lowest=True, duplicates="drop")
    g = m.groupby("bin")["dmu_CET"]
    binned = pd.DataFrame({
        "bin_left":  [b.left  for b in g.mean().index],
        "bin_right": [b.right for b in g.mean().index],
        "mean_dmu":  g.mean().values,
        "sem_dmu":   (g.std().values/np.sqrt(g.count().values)),
        "count":     g.count().values
    })
    binned.to_csv(os.path.join(args.outdir, "dmu_binned_CET.csv"), index=False)

    plt.figure(figsize=(9,6))
    xc = 0.5*(binned["bin_left"]+binned["bin_right"])
    plt.errorbar(xc, binned["mean_dmu"], yerr=binned["sem_dmu"], fmt="o-")
    plt.xlabel(args.dens_col + " (quantile bins)")
    plt.ylabel("<Δμ_CET> ± SEM")
    plt.title("Mean Δμ_CET vs LOS density (CET linear)")
    plt.tight_layout()
    plt.savefig(os.path.join(args.outdir, "dmu_binned_CET.png"), dpi=160)
    plt.close()

    print("[OK] CET test completed.")
    print(f"  N used           : {len(m)}")
    print(f"  Spearman rho, p  : {rho:.3f}, {pval:.3g}")
    print(f"  linear slope, p  : {slope:.4g}, {p_lin:.3g}")
    print(f"Outputs in: {args.outdir}")

if __name__ == "__main__":
    main()